RestaurantApplication/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantApplication.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        // This controller is to serve a one stop view to all the restaurant management actions
        // The view contains links to all other controller's action which belongs to the Admin User
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

RestaurantApplication/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Net.Http;
using System.Web.Http.Results;
using System.Web.Mvc;
using RestaurantApplication.Models;
using System.Web.Script.Serialization;

namespace RestaurantApplication.Controllers
{
    public class BookingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private readonly Client client = new Client();
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        [Authorize]
        [HttpGet]
        // GET: Bookings
        // This is for the admin to retrieve and view all the current bookings in the system
        public ActionResult Index()
        {
            //// http client implementation
            //string url = "BookingsData/GetBookings";
            //var resp = client.ExecuteGet(url);

            //IEnumerable<Booking> bookings = resp.ReadAsAsync<IEnumerable<Booking>>().Result;


            //datacontroller implementation
            BookingsDataController bookingsDataController = new BookingsDataController();
            IEnumerable<Booking> bookings = bookingsDataController.GetBookings();
            return View(bookings);
        }

        [Authorize]
        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // httpClient implementation
            //string url = "BookingsData/GetBooking/" + Convert.ToInt32(id);
            //var resp = client.ExecuteGet(url);
            //Booking booking = resp.ReadAsAsync<Booking>().Result;


            // datacontroller implementation
            BookingsDataController bookingsDataController = new BookingsDataController();
            System.Web.Http.IHttpActionResult actionResult = bookingsDataController.GetBooking(Convert.ToInt32(id));

            OkNegotiatedContentResult<Booking> contentResult = actionResult as OkNegotiatedContentResult<Booking>;
            if (contentResult == null)
            {
                return HttpNotFound();
            }
            Booking booking = contentResult.Content;

            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // public facing action to show the booking details with  sensitive information removed
        public ActionResult ViewBooking(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // httpClient implementation
            //string url = "BookingsData/ViewBooking/" + Convert.ToInt32(id);
            //var resp = client.ExecuteGet(url);
            //BookingDto bookingDetail = resp.ReadAsAsync<BookingDto>().Result;
            //if (bookingDetail == null)
            //{
            //    return HttpNotFound();
            //}

            // datacontroller implementation
            BookingsDataController bookingsDataController = new BookingsDataController();
            System.Web.Http.IHttpActionResult actionResult = bookingsDataController.ViewBooking(Convert.ToInt32(id));
            OkNegotiatedContentResult<BookingDto> contentResult = actionResult as OkNegotiatedContentResult<BookingDto>;
            if (contentResult == null)
            {
                return HttpNotFound();
            }
            BookingDto bookingDetail = contentResult.Content;

            return View(bookingDetail);
        }

        // GET: Bookings/Create
        // Action to generate the view to create the booking
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bookings/Create
        // Action for users to create a booking at the table
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingID,TableNumber,NumberOfOccupants,Allergies,BookingDateTime,UserID,EmailID,PhoneNumber,BookingName")] Booking booking)
        {
            // verify the model state before sending the booking object to controller
            if (ModelState.IsValid)
            {
                // http client
                //string url = "BookingsData/CreateBooking";
                //string jsonPayLoad = jss.Serialize(booking);
                //var resp = client.ExecutePost(url, jsonPayLoad);
                //// if the post is successful read the respose and redirect the user to the booking page
                //if (resp.IsSuccessStatusCode)
                //{
                //    var responseContent = resp.Content;
                //    string responseString = responseContent.ReadAsStringAsync().Result;
                //    string newBookingId = jss.Deserialize<Booking>(responseString).BookingID.ToString();
                //    return RedirectToAction("ViewBooking/" + newBookingId);
                //}
                //else
                //{
                //    return RedirectToAction("Error");
                //}

                // datacontroller
                BookingsDataController bookingsDataController = new BookingsDataController();
                System.Web.Http.IHttpActionResult actionResult = bookingsDataController.CreateBooking(booking);
                return RedirectToAction("ViewBooking/" + booking.BookingID);
            }
            // if model state is not valid, redirect the user to the booking page again.
            // enhancement : Add an error message to say the booking creation failed.
            return View(booking);
        }

        [Authorize]
        // GET: Bookings/Edit/5
        // Method to edit the booking details
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // httpClient implementation
            //string url = "BookingsData/GetBooking/" + Convert.ToInt32(id);
            //var resp = client.ExecuteGet(url);
            //Booking booking = resp.ReadAsAsync<Booking>().Result;

            // controller implementation
            BookingsDataController bookingsDataController = new BookingsDataController();
            System.Web.Http.IHttpActionResult actionResult = bookingsDataController.GetBooking(Convert.ToInt32(id));
            OkNegotiatedContentResult<Booking> contentResult = actionResult as OkNegotiatedContentResult<Booking>;
            if (contentResult == null)
            {
                return HttpNotFound();
            }
            Booking booking = contentResult.Content;
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // Method to receive the edited booking details
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingID,TableNumber,NumberOfOccupants,Allergies,BookingDateTime,UserID,Status,EmailID,PhoneNumber,BookingName")] Booking booking)
        {
            // Preliminary inspection of ModelState validation before calling the API
            if (ModelState.IsValid)
            {
                // http client
                //string url = "BookingsData/EditBooking/" + Convert.ToInt32(booking.BookingID);
                //string jsonPayLoad = jss.Serialize(booking);
                //var resp = client.ExecutePost(url, jsonPayLoad);
                //// if the post is successful read the respose and redirect the user to the booking page
                //if (resp.IsSuccessStatusCode)
                //{
                //    return RedirectToAction("Index");
                //}
                //else
                //{
                //    return RedirectToAction("Error");
                //}

                // controller
                BookingsDataController bookingsDataController = new BookingsDataController();
                System.Web.Http.IHttpActionResult actionResult = bookingsDataController.EditBooking(booking.BookingID, booking);
                return RedirectToAction("Index");
            } 
            else
            {
                System.Diagnostics.Debug.WriteLine("ModelState Invalid");
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // httpClient implementation
            //string url = "BookingsData/GetBooking/" + Convert.ToInt32(id);
            //var resp = client.ExecuteGet(url);
            //Booking booking = resp.ReadAsAsync<Booking>().Result;

            // controller implementation
            BookingsDataController bookingsDataController = new BookingsDataController();
            System.Web.Http.IHttpActionResult actionResult = bookingsDataController.GetBooking(Convert.ToInt32(id));
            OkNegotiatedContentResult<Booking> contentResult = actionResult as OkNegotiatedContentResult<Booking>;
            if (contentResult == null)
            {
                return HttpNotFound();
            }
            Booking booking = contentResult.Content;
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            // httpclient implementation
            //string url = "BookingsData/DeleteBooking/" + Convert.ToInt32(id);
            //string jsonPayLoad = null;
            //var resp = client.ExecutePost(url, jsonPayLoad);
            // controller implementation

RestaurantApplication/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using RestaurantApplication.Models;
using RestaurantApplication.Models.ViewModel;
using System.Web.Script.Serialization;

namespace RestaurantApplication.Controllers
{
    // Food controller is mainly user facing controller, FoodsController is for the Admin
    // This will be combined at a later stage
    public class FoodController : Controller
    {
        //private static readonly HttpClient client;
        //private JavaScriptSerializer jss = new JavaScriptSerializer();
        private readonly Client client = new Client();

        // GET: Food/List
        // List is shown when a user directly clicks on the Menu link in th navbar
        public ActionResult List()
        {
            //retrieve the list of food items

            // HttpClient Implementation
            //string url = "FoodData/ListFoods";
            //var resp = client.ExecuteGet(url);
            //IEnumerable<FoodDto> foods = resp.ReadAsAsync<IEnumerable<FoodDto>>().Result;

            //Datacontroller implementation
            FoodDataController foodDataController = new FoodDataController();
            IEnumerable<FoodDto> foods = foodDataController.ListFoods();

            return View(foods);
        }

        // Post : Food/ListNew
        // This function is executed when a client books the table with their credentials
        // Once the booking is confirmed a button to order the food will be shown in the booking status page
        // On clicking the button, the booking ID is also passed to this view as a hidden form so that the
        // payment page can be auto-filled by the system.
        [HttpPost]
        public ActionResult ListNew(int bookingId)
        {
            // retrieve the list of food items

            // HttpClient Implementation
            //string url = "FoodData/ListFoods";
            //var resp = client.ExecuteGet(url);
            //IEnumerable<FoodDto> foods = resp.ReadAsAsync<IEnumerable<FoodDto>>().Result;

            // datacontroller implementation
            FoodDataController foodDataController = new FoodDataController();
            IEnumerable<FoodDto> foods = foodDataController.ListFoods();

            BookingIDFoodMenu foodsMenu = new BookingIDFoodMenu
            {
                Food = foods,
                BookingID = (int)bookingId
            };

            return View(foodsMenu);
        }

        // GET: Food/Details/5
        // Not implemented in the Views yet, this is for the customer to see a detailed description of the food item
        // Might include this at a later stage
        public ActionResult Details(int id)
        {
            // HttpClient Implementation
            string url = "FoodData/FindFood/" + id;
            var resp = client.ExecuteGet(url);
            FoodDto foods = resp.ReadAsAsync<FoodDto>().Result;
            return View(foods);
        }

    }
}

RestaurantApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Firehouse Pizzeria</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Pizzeria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Menu", "List", "Food")</li>
                    <li>@Html.ActionLink("Book Table", "Create", "Bookings")</li>
                    <li>@Html.ActionLink("Manage", "Index", "Admin")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FireHouse Pizzeria</p>
        </footer>
    </div>


</body>
</html>

RestaurantApplication/Views/Shared/_UserPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Firehouse Pizzeria</title>
    @*@Styles.Render("~/Content/bootstrap5")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap5")*@
    <link href="/Content/bootstrap5/bootstrap.css" rel="stylesheet" />
    <link href="/Content/User.css" rel="stylesheet" />

    <script src="/Scripts/modernizr-2.8.3.js"></script>

    <script src="/Scripts/jquery-3.4.1.js"></script>

    <script src="/Scripts/bootstrap5/bootstrap.bundle.min.js"></script>

    @RenderSection("scripts", required: false)


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                @*@Html.ActionLink("ABC Pizzeria", "Index", new { controller = "Home" }, new { @class = "navbar-brand navbar-brand-centered" })*@
                @*<img src="~/Content/images/PizzaLogo.png" alt="" width="100" />*@
                <a href="@Url.Action("Index", "Home")" title="Logo" class="navbar-brand" id="brandNav">
                    <img alt="" src="@Url.Content("~/Content/images/PizzaLogo.png")" width="200">
                    @*Firehouse Pizzeria*@
                </a>
                @*<a class="navbar-brand" href="#">ABC Pizzeria</a>*@
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                @*<li class="nav-item">
            @Html.ActionLink("Home", "Index", new { controller = "Home" }, new { @class = "nav-link text-light" })
        </li>*@
                <li class="nav-item">
                    @Html.ActionLink("about us", "Index", new { controller = "Home" }, new { @class = "nav-link text-light"})
                </li>
                <li class="nav-item">
                    @Html.ActionLink("food & drink menu", "List", new { controller = "Food" }, new { @class = "nav-link text-light" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("book a table", "Create", new { controller = "Bookings" }, new { @class = "nav-link text-light" })
                </li>
                @*<li class="nav-item">
            @Html.ActionLink("Book Table", "Create", new { controller = "Bookings" }, new { @class = "nav-link text-light" })
        </li>*@
                @*<li class="nav-item">
            @Html.ActionLink("Manage", "Index", new { controller = "Admin" }, new { @class = "nav-link text-dark" })
        </li>*@
            </ul>
                @*@Html.Partial("_LoginPartial")*@
                @*@Html.ActionLink("Manage", "Index", new { controller = "Admin" }, new { @class = "nav-link text-light" })*@
                @*@Html.ActionLink("Book Table", "Create", new { controller = "Bookings" }, new { @class = "nav-link text-light" })*@
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="user-body">
            @RenderBody()
        </div>
        
        <hr />
        <footer style="text-align:center; background-color:rgb(0 0 0 / 0.77); padding:40px;">
            <p>&copy; @DateTime.Now.Year - Firehouse Pizzeria : Navaneeth Ashok</p>
        </footer>
    </div>


</body>
</html>